/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.User;
import model.Equipment;
import service.EquipmentService;


public class CheckoutFrame extends javax.swing.JFrame
{

    private final User currentUser;
    private final service.EquipmentService equipmentService = new EquipmentService();
    private final service.CheckoutService checkoutService = new service.CheckoutService();
    private DefaultTableModel tableModel;
    
    public CheckoutFrame(User user)
    {
        initComponents();
        setLocationRelativeTo(null);
        
        this.currentUser = user;
        
        setupTable();
        loadAvailableEquipment();
    }
    
    private void setupTable()
    {
        tableModel = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Equipment ID", "Name", "Category", "Status", "Location"})
        {
            @Override
            public boolean isCellEditable(int row, int colum)
            {
                return false;
            }
        };
        
        tblAvailableEquipment.setModel(tableModel);
        tblAvailableEquipment.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAvailableEquipment.getTableHeader().setReorderingAllowed(false);
    }
    
    private void loadAvailableEquipment() 
    {
        tableModel.setRowCount(0);

        List<Equipment> list = equipmentService.getAllEquipment();

        for (Equipment e : list) 
        {
            if ("Available".equalsIgnoreCase(e.getStatus())) 
            {
                tableModel.addRow(new Object[]{
                    e.getEquipmentId(),
                    e.getName(),
                    e.getCategory(),
                    e.getStatus(),
                    e.getLocation()
                });
            }
        }
    }
    
    private Equipment findEquipmentById(String equipmentId)
    {
        for ( Equipment e : equipmentService.getAllEquipment())
        {
            if (e.getEquipmentId().equals(equipmentId))
            {
                return e;
            }
        }
        return null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlHeader = new javax.swing.JPanel();
        lblCheckoutEquipment = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableEquipment = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 600));

        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblCheckoutEquipment.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCheckoutEquipment.setText("Checkout Equipment");
        pnlHeader.add(lblCheckoutEquipment, java.awt.BorderLayout.NORTH);

        tblAvailableEquipment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblAvailableEquipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAvailableEquipment.setRowHeight(24);
        jScrollPane1.setViewportView(tblAvailableEquipment);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pnlFooter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlFooter.setLayout(new java.awt.BorderLayout());

        btnCheckout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCheckout.setText("Check out");
        btnCheckout.setPreferredSize(new java.awt.Dimension(170, 35));
        btnCheckout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCheckoutActionPerformed(evt);
            }
        });
        pnlFooter.add(btnCheckout, java.awt.BorderLayout.CENTER);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMessage.setPreferredSize(new java.awt.Dimension(170, 25));
        pnlFooter.add(lblMessage, java.awt.BorderLayout.PAGE_START);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(170, 35));
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        pnlFooter.add(btnBack, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        new MainMenuFrame(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCheckoutActionPerformed
    {//GEN-HEADEREND:event_btnCheckoutActionPerformed

        
        int row = tblAvailableEquipment.getSelectedRow();

        if (row == -1) 
        {
            lblMessage.setText("Please select an equipment item to checkout.");
            return;
        }

        String equipmentId = (String) tableModel.getValueAt(row, 0);

        Equipment selected = findEquipmentById(equipmentId);
        if (selected == null) 
        {
            lblMessage.setText("Error: Selected equipment not found.");
            return;
        }

        // Verify availability (SRS 3.2.3.2 / 3.2.3.5)
        if (!"Available".equalsIgnoreCase(selected.getStatus())) 
        {
            lblMessage.setText("Checkout blocked: equipment is not available.");
            loadAvailableEquipment(); // refresh view
            return;
        }

        // Record checkout info later (CheckoutRecord) — for now update status (SRS 3.2.3.4)
        boolean ok = checkoutService.checkoutEquipment(currentUser, selected);

        if ( ok )
        {
            lblMessage.setText("Check out: " + selected.getName());
            loadAvailableEquipment();
        }
        else
        {
            lblMessage.setText("Checkout blocked: equipment is not available.");
        }

        lblMessage.setText("Checked out: " + selected.getName());
        loadAvailableEquipment(); // refresh table (item disappears)
        

    }//GEN-LAST:event_btnCheckoutActionPerformed

    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheckoutEquipment;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblAvailableEquipment;
    // End of variables declaration//GEN-END:variables
}
