/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.LoginFrame;
import UI.ViewInventoryFrame;
import model.User;





public class MainMenuFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainMenuFrame
     */
    private User currentUser;
    
    public MainMenuFrame(User user)
    {
        initComponents();
        // sets the window to open in the middle of the screen
        this.setLocationRelativeTo( null );
        
        this.currentUser = user;        
        lblLoggedInUser.setText( "Logged in as: " + user.getRole() );

        applyRolePermissions();

    }
    
    private void applyRolePermissions()
    {
        if ( !currentUser.getRole().equalsIgnoreCase( "Admin" ) )
        {
            btnReport.setEnabled( false );
            btnManageEquipment.setEnabled( false );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLoggedInUser = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        btnCheckOut = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnManageEquipment = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnViewInventory = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblVersion = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment Checkout System - Main Menu");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));

        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setText("Equipment Checkout System");
        pnlHeader.add(lblTitle, java.awt.BorderLayout.CENTER);

        lblLoggedInUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLoggedInUser.setText("Logged in as: Admin");
        pnlHeader.add(lblLoggedInUser, java.awt.BorderLayout.PAGE_END);

        pnlCenter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlCenter.setLayout(new java.awt.GridBagLayout());

        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCheckOut.setText("Checkout Equipment");
        btnCheckOut.setPreferredSize(new java.awt.Dimension(400, 40));
        btnCheckOut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCheckOutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlCenter.add(btnCheckOut, gridBagConstraints);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReturn.setText("Return Equipment");
        btnReturn.setPreferredSize(new java.awt.Dimension(400, 40));
        btnReturn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReturnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlCenter.add(btnReturn, gridBagConstraints);

        btnManageEquipment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManageEquipment.setText("Manage Equipment");
        btnManageEquipment.setPreferredSize(new java.awt.Dimension(400, 40));
        btnManageEquipment.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnManageEquipmentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlCenter.add(btnManageEquipment, gridBagConstraints);

        btnReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReport.setText("Generate Report");
        btnReport.setPreferredSize(new java.awt.Dimension(400, 40));
        btnReport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlCenter.add(btnReport, gridBagConstraints);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setPreferredSize(new java.awt.Dimension(400, 40));
        btnLogOut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLogOutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        pnlCenter.add(btnLogOut, gridBagConstraints);

        btnViewInventory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewInventory.setText("View Inventory");
        btnViewInventory.setPreferredSize(new java.awt.Dimension(400, 40));
        btnViewInventory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewInventoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        pnlCenter.add(btnViewInventory, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblVersion.setText("Version 1.0 - Internal Use Only");
        jPanel1.add(lblVersion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLogOutActionPerformed
    {//GEN-HEADEREND:event_btnLogOutActionPerformed
        new LoginFrame().setVisible( true );
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewInventoryActionPerformed
    {//GEN-HEADEREND:event_btnViewInventoryActionPerformed
        new ViewInventoryFrame(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewInventoryActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCheckOutActionPerformed
    {//GEN-HEADEREND:event_btnCheckOutActionPerformed
        new CheckoutFrame(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReturnActionPerformed
    {//GEN-HEADEREND:event_btnReturnActionPerformed
        new ReturnFrame( currentUser ).setVisible( true );
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnManageEquipmentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnManageEquipmentActionPerformed
    {//GEN-HEADEREND:event_btnManageEquipmentActionPerformed
        new ManageEquipmentFrame( currentUser ).setVisible( true );
        this.dispose();
    }//GEN-LAST:event_btnManageEquipmentActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReportActionPerformed
    {//GEN-HEADEREND:event_btnReportActionPerformed
        new ReportsFrame(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageEquipment;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
