/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.User;
import model.Equipment;
import service.CheckoutService;
import service.EquipmentService;


public class ReturnFrame extends javax.swing.JFrame
{
    private final User currentUser;
    private final EquipmentService equipmentService = new EquipmentService();
    private final CheckoutService checkoutService = new CheckoutService();
    private DefaultTableModel tableModel;
    
    public ReturnFrame(User user)
    {
        initComponents();
        this.setLocationRelativeTo(null );
        
        this.currentUser = user;
        
        setupTable();
        loadCheckedOutEquipment();
    }
    
    private void setupTable()
    {
        tableModel = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Equipment ID", "Name", "Category", "Status", "Location"})
        {
            @Override
            public boolean isCellEditable(int row, int column)
                {
                    return false;
                }
        };
        
        tblCheckedOutEquipment.setModel(tableModel);
        tblCheckedOutEquipment.setSelectionMode( javax.swing.ListSelectionModel.SINGLE_SELECTION );
        tblCheckedOutEquipment.getTableHeader().setReorderingAllowed( false );
    }
    
    private void loadCheckedOutEquipment()
    {
        tableModel.setRowCount(0);
        
        List<Equipment> list = equipmentService.getAllEquipment();
        
        for ( Equipment e : list )
        {
            if ( "Checked Out".equalsIgnoreCase(e.getStatus()))
            {
                tableModel.addRow( new Object[] 
                {
                    e.getEquipmentId(),
                    e.getName(),
                    e.getCategory(),
                    e.getStatus(),
                    e.getLocation()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlfooter = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCheckedOutEquipment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Return Equipment");
        pnlHeader.add(lblTitle, java.awt.BorderLayout.CENTER);

        pnlfooter.setLayout(new java.awt.GridLayout(3, 0));

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlfooter.add(lblMessage);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReturn.setText("Return Selected");
        btnReturn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReturnActionPerformed(evt);
            }
        });
        pnlfooter.add(btnReturn);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        pnlfooter.add(btnBack);

        tblCheckedOutEquipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCheckedOutEquipment);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlfooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCenter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlfooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        new MainMenuFrame( currentUser ).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReturnActionPerformed
    {//GEN-HEADEREND:event_btnReturnActionPerformed
        int row = tblCheckedOutEquipment.getSelectedRow();
        
        if ( row == -1 )
        {
            lblMessage.setText("Please select an equipment item to return." );
            return;
        }
        
        String equipmentId = ( String ) tableModel.getValueAt(row, 0 );
        
        Equipment selected = findEquipmentById( equipmentId );
        if ( selected == null )
        {
            lblMessage.setText("Error: Selected equipment not found.");
            return;
        }

        // Only allow return if checked out
        if (!"Checked Out".equalsIgnoreCase(selected.getStatus()))
        {
            lblMessage.setText("Return blocked: item is not currently checked out.");
            loadCheckedOutEquipment();
            return;
        }

        checkoutService.returnEquipment(selected );

        lblMessage.setText( "Returned: " + selected.getName() );
        loadCheckedOutEquipment(); // refresh table (item disappears)
    }//GEN-LAST:event_btnReturnActionPerformed
    
    private Equipment findEquipmentById( String equipmentId )
    {
        for ( Equipment e : equipmentService.getAllEquipment() )
        {
            if ( e.getEquipmentId().equalsIgnoreCase(equipmentId) )
            {
               return e;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlfooter;
    private javax.swing.JTable tblCheckedOutEquipment;
    // End of variables declaration//GEN-END:variables
}
