/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import model.User;
import UI.MainMenuFrame;
import service.EquipmentService;


/**
 *
 * @author dscho
 */
public class ViewInventoryFrame extends javax.swing.JFrame
{

    private model.User currentUser;
    private javax.swing.table.DefaultTableModel tableModel;
    private service.EquipmentService equipmentService = new service.EquipmentService();
    
    
    public ViewInventoryFrame(User user)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.currentUser = user;
        
        setupTable();
        loadInventoryTable();
        setupFilters();      
        
    }
    
    private void setupTable()
    {
        tableModel = new javax.swing.table.DefaultTableModel( new Object[][] {}, new String[] { "Equipment ID", 
        "Name", "Category", "Status", "Location"})
                {
                    @Override
                    public boolean isCellEditable( int row, int column )
                    {
                        return false;
                    }
                };
        
        tblInventory.setModel(tableModel);
        tblInventory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void loadInventoryTable() 
    {
        tableModel.setRowCount(0);

        // If your EquipmentService already has a method that returns a list, use it here.
        java.util.List<model.Equipment> equipmentList = equipmentService.getAllEquipment();

        for (model.Equipment e : equipmentList) {
            tableModel.addRow(new Object[] {
                e.getEquipmentId(),
                e.getName(),
                e.getCategory(),
                e.getStatus(),
                e.getLocation()
            });
        }
    }
    
    private void setupFilters() 
    {
        // Simple approach: start with "All" only, then populate from inventory
        cmbCategory.removeAllItems();
        cmbStatus.removeAllItems();
        cmbLocation.removeAllItems();

        cmbCategory.addItem("All");
        cmbStatus.addItem("All");
        cmbLocation.addItem("All");

        java.util.Set<String> categories = new java.util.HashSet<>();
        java.util.Set<String> statuses = new java.util.HashSet<>();
        java.util.Set<String> locations = new java.util.HashSet<>();

        for (model.Equipment e : equipmentService.getAllEquipment()) 
        {
            categories.add(e.getCategory());
            statuses.add(String.valueOf(e.getStatus()));
            locations.add(e.getLocation());
        }

        for (String s : categories) cmbCategory.addItem(s);
        for (String s : statuses) cmbStatus.addItem(s);
        for (String s : locations) cmbLocation.addItem(s);
    }



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblEquipmentInventory = new javax.swing.JLabel();
        pnlFilters = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblLocation = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        btnApplyFilters = new javax.swing.JButton();
        btnClearFilters = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        scpInventory = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment Inventory");
        setSize(new java.awt.Dimension(900, 600));

        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblEquipmentInventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEquipmentInventory.setText("Equipment Inventory");
        pnlHeader.add(lblEquipmentInventory, java.awt.BorderLayout.CENTER);

        pnlFilters.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlFilters.setLayout(new java.awt.GridBagLayout());

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCategory.setText("Category");
        pnlFilters.add(lblCategory, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 14);
        pnlFilters.add(cmbCategory, gridBagConstraints);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStatus.setText("Status");
        pnlFilters.add(lblStatus, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 14);
        pnlFilters.add(cmbStatus, gridBagConstraints);

        lblLocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLocation.setText("Location");
        pnlFilters.add(lblLocation, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 14);
        pnlFilters.add(cmbLocation, gridBagConstraints);

        btnApplyFilters.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnApplyFilters.setText("Apply");
        btnApplyFilters.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnApplyFiltersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        pnlFilters.add(btnApplyFilters, gridBagConstraints);

        btnClearFilters.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClearFilters.setText("Clear");
        btnClearFilters.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearFiltersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        pnlFilters.add(btnClearFilters, gridBagConstraints);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpInventory.setViewportView(tblInventory);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpInventory)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );

        pnlFooter.setLayout(new java.awt.BorderLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        pnlFooter.add(btnBack, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFilters, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyFiltersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnApplyFiltersActionPerformed
    {//GEN-HEADEREND:event_btnApplyFiltersActionPerformed
        String category = (String) cmbCategory.getSelectedItem();
        String status = (String) cmbStatus.getSelectedItem();
        String location = (String) cmbLocation.getSelectedItem();

        tableModel.setRowCount(0);

        for (model.Equipment e : equipmentService.getAllEquipment())
        {
            boolean match = true;

            if (!"All".equals(category) && !e.getCategory().equals(category)) match = false;
            if (!"All".equals(status) && !e.getStatus().equals(status)) match = false;
            if (!"All".equals(location) && !e.getLocation().equals(location)) match = false;

            if (match)
            {
                tableModel.addRow(new Object[]
                {
                    e.getEquipmentId(),
                    e.getName(),
                    e.getCategory(),
                    e.getStatus(),
                    e.getLocation()
                });
            }
        }
    }//GEN-LAST:event_btnApplyFiltersActionPerformed

    private void btnClearFiltersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearFiltersActionPerformed
    {//GEN-HEADEREND:event_btnClearFiltersActionPerformed
        cmbCategory.setSelectedItem("All");
        cmbStatus.setSelectedItem("All");
        cmbLocation.setSelectedItem("All");
        loadInventoryTable();
    }//GEN-LAST:event_btnClearFiltersActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        new MainMenuFrame(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyFilters;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearFilters;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblEquipmentInventory;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlFilters;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JScrollPane scpInventory;
    private javax.swing.JTable tblInventory;
    // End of variables declaration//GEN-END:variables
}
